;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Biome.Desert",DevComment="")
+GameplayTagList=(Tag="Biome.Flora",DevComment="")
+GameplayTagList=(Tag="Biome.Ice",DevComment="")
+GameplayTagList=(Tag="Biome.Magnetic",DevComment="")
+GameplayTagList=(Tag="Biome.Mirror",DevComment="")
+GameplayTagList=(Tag="Biome.Moon",DevComment="")
+GameplayTagList=(Tag="Biome.Ocean",DevComment="")
+GameplayTagList=(Tag="Biome.Stone",DevComment="")
+GameplayTagList=(Tag="Biome.Verdant",DevComment="")
+GameplayTagList=(Tag="Biome.Volcanic",DevComment="")
+GameplayTagList=(Tag="MiniGame.FireOut",DevComment="")
+GameplayTagList=(Tag="MiniGame.FixWires",DevComment="")
+GameplayTagList=(Tag="MiniGame.LightsOff",DevComment="")
+GameplayTagList=(Tag="MiniGame.PlugHoles",DevComment="")
+GameplayTagList=(Tag="MiniGame.Signal",DevComment="")
+GameplayTagList=(Tag="Module.Scanner",DevComment="")
+GameplayTagList=(Tag="Module.Shield",DevComment="")
+GameplayTagList=(Tag="Module.Turret",DevComment="")
+GameplayTagList=(Tag="Recovery.Energy",DevComment="")
+GameplayTagList=(Tag="Recovery.Food",DevComment="")
+GameplayTagList=(Tag="Recovery.Water",DevComment="")

